name: CI/CD Pipeline

on: 
  push: 
    branches: 
      - main
  pull_request:
    branches: 
      - main
  
  jobs:
    test:
      runs-on: ubuntu-latest

      steps: 
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Set up Docker Compose
          uses: docker/setup-qemu-action@v2

        - name: Ensure Docker Compose is available
          run: docker-compose version

        - name: Copy .env.example to .env
          run: cp ./week-25.1/.env.example ./week-25.1/.env

        - name: Run integration script
          run: cd week-25.1 && npx run test:integration